In [1]:
#Viewing some values

import numpy as np
from scipy.io import arff
import pandas as pd

data = arff.loadarff('./emotions-train.arff') #change the address file
df = pd.DataFrame(data[0])

df.head()

Mean_Acc1298_Mean_Mem40_Centroid  Mean_Acc1298_Mean_Mem40_Rolloff  \
0                          0.034741                         0.089665   
1                          0.081374                         0.272747   
2                          0.110545                         0.273567   
3                          0.042481                         0.199281   
4                          0.074550                         0.140880   

   Mean_Acc1298_Mean_Mem40_Flux  Mean_Acc1298_Mean_Mem40_MFCC_0  \
0                      0.091225                      -73.302422   
1                      0.085733                      -62.584437   
2                      0.084410                      -65.235325   
3                      0.093447                      -80.305152   
4                      0.079789                      -93.697749   

   Mean_Acc1298_Mean_Mem40_MFCC_1  Mean_Acc1298_Mean_Mem40_MFCC_2  \
0                        6.215179                        0.615074   
1                        3.183163                       -0.218145   
2                        2.794964                        0.639047   
3                        5.824409                        0.648848   
4                        5.543229                        1.064262   

   Mean_Acc1298_Mean_Mem40_MFCC_3  Mean_Acc1298_Mean_Mem40_MFCC_4  \
0                        2.037160                        0.804065   
1                        0.163038                        0.620251   
2                        1.281297                        0.757896   
3                        1.754870                        1.495532   
4                        0.899152                        0.890336   

   Mean_Acc1298_Mean_Mem40_MFCC_5  Mean_Acc1298_Mean_Mem40_MFCC_6  ...  \
0                        1.301409                        0.558576  ...   
1                        0.458514                        0.041426  ...   
2                        0.489412                        0.627636  ...   
3                        0.739909                        0.809644  ...   
4                        0.702328                        0.490685  ...   

   BH_HighLowRatio    BHSUM1    BHSUM2    BHSUM3  amazed-suprised  \
0              2.0  0.245457  0.105065  0.405399             b'0'   
1              2.0  0.343547  0.276366  0.710924             b'1'   
2              3.0  0.188693  0.045941  0.457372             b'0'   
3              2.0  0.102839  0.241934  0.351009             b'0'   
4              2.0  0.195196  0.310801  0.683817             b'0'   

   happy-pleased  relaxing-calm  quiet-still  sad-lonely  angry-aggresive  
0           b'1'           b'1'         b'0'        b'0'             b'0'  
1           b'0'           b'0'         b'0'        b'0'             b'1'  
2           b'1'           b'0'         b'0'        b'0'             b'1'  
3           b'0'           b'1'         b'0'        b'0'             b'0'  
4           b'0'           b'0'         b'1'        b'0'             b'0'  

[5 rows x 78 columns]

# For Training

In [2]:
data, meta = arff.loadarff('./emotions-train.arff') #72 numeric, 6 labels 
#print(data) 
data[390][77] #391x78 #no. of data point=391

x_train=[]
y_train=[]
x_t = np.zeros((391, 1))
y_t = np.zeros((391, 1))

for i in range(391):
    for j in range(72):
        x_t=data[i][j]
        #print(x_t)
        x_train.append(x_t)
        
for i in range(391):
    for j in range(72,78):
        y_t=data[i][j]
        #print(y_t)
        y_train.append(y_t)
        
x_train=np.array(x_train)
x_train=np.reshape(x_train, (391, 72))
x_train
y_train=np.array(y_train, dtype='int64')
y_train=np.reshape(y_train, (391, 6))
x_train.shape


(391, 72)

In [3]:
np.save('Xtrain_2021-11-24.npy', x_train)
np.save('Ytrainbin_2021-11-24.npy', y_train)
np.load("Ytrainbin_2021-11-24.npy")
#y_train
#y_train[1].dot(2**np.arange(y_train[0].size)[::-1])

array([[0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       ...,
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0]])

In [4]:
#Converting y_train into decimal form
def bool2int(x):
    y = 0.0
    for i,j in enumerate(x):
        y += j<<i
    return y

y_train_decimal = [bool2int(x[::-1]) for x in y_train]
y_train_decimal = np.array(y_train_decimal)
#y_train_decimal

np.save('Ytrain_2021-11-24.npy', y_train_decimal)
np.load('Ytrain_2021-11-24.npy')

array([24., 33., 17.,  8.,  4., 24., 48.,  1., 48., 14., 24.,  8., 32.,
       10.,  2., 33., 14., 24.,  3., 14., 33., 16., 16.,  1.,  1.,  9.,
        8., 49., 16.,  8.,  1., 12., 33.,  1., 48., 24., 14., 24., 48.,
       33., 16., 34., 14., 24., 48., 24., 14., 24.,  1., 33.,  1., 11.,
        1., 33., 33., 14., 14., 10., 48., 18.,  3., 24., 12., 14., 14.,
       33.,  8., 14., 24., 33.,  2., 33.,  1., 56., 40., 11., 24., 24.,
        1.,  1.,  1., 32., 10., 32.,  8., 12., 10., 12.,  1., 17.,  2.,
       33., 10., 24., 33.,  1., 14., 33.,  1., 48.,  8.,  1.,  1.,  8.,
       33., 24., 33., 48.,  1., 32., 14., 33.,  1.,  3., 28., 24., 49.,
       10., 10.,  9., 14.,  1., 24., 33.,  6., 24., 33., 12.,  1., 32.,
       24., 48., 24.,  3., 32.,  1., 32., 24., 14., 33., 10.,  1.,  8.,
       33., 33., 48., 16., 32., 33.,  1., 16., 32.,  6., 33., 33., 28.,
       10.,  6.,  1., 14.,  1.,  1., 16.,  8., 33.,  1., 10.,  1., 14.,
        1., 32., 10., 14.,  1.,  1., 33.,  1., 16., 32., 24., 33

# For Testing

In [5]:
data2, meta = arff.loadarff('/Users/upasanathakuria/Desktop/emotions/emotions-test.arff') #72 numeric, 6 labels (202x78)
#print(data2) 
data2[0][0]

0.036299

In [6]:
x_test=[]
y_test=[]
x_te = np.zeros((202, 1))
y_te = np.zeros((202, 1))

for i in range(202):
    for j in range(72):
        x_te=data2[i][j]
        #print(x_t)
        x_test.append(x_te)
        
for i in range(202):
    for j in range(72,78):
        y_te=data2[i][j]
        #print(y_t)
        y_test.append(y_te)
x_test=np.array(x_test)
x_test=np.reshape(x_test, (202, 72))
x_test
y_test=np.array(y_test, dtype='int64')
y_test=np.reshape(y_test, (202, 6))
y_test.shape

(202, 6)

In [7]:
np.save('Xtest_2021-11-24.npy', x_test)
np.save('Ytestbin_2021-11-24.npy', y_test)

In [8]:
np.load("Ytestbin_2021-11-24.npy")

array([[0, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       ...,
       [0, 0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [9]:
#Converting y_test into decimal form
def bool2int(x):
    y = 0.0
    for i,j in enumerate(x):
        y += j<<i
    return y

y_test_decimal = [bool2int(x[::-1]) for x in y_test]
y_test_decimal = np.array(y_test_decimal)
#y_train_decimal

np.save('Ytest_2021-11-24.npy', y_test_decimal)
np.load('Ytest_2021-11-24.npy')
#y_test_decimal.shape

array([14., 33.,  2., 24.,  2., 10., 33., 14.,  3., 14., 28., 14., 48.,
       35., 33., 14.,  8.,  6., 48., 24., 49., 14., 33., 34., 14., 14.,
       14.,  1., 48., 24., 14.,  3.,  8., 24., 48.,  6., 12.,  8., 17.,
        1., 33., 10., 10.,  6.,  6., 14., 33., 33., 16., 24.,  1., 14.,
        6.,  8.,  6., 49., 48.,  6., 24.,  6.,  8.,  6., 48., 33., 24.,
        8., 24., 14., 33., 14., 56., 24.,  1.,  1.,  6., 17., 48.,  8.,
       12.,  6., 12., 10.,  1.,  1., 24.,  2., 33., 14., 33., 34., 14.,
       24., 33., 24.,  6., 48.,  1., 33.,  3., 16.,  6., 24.,  6.,  1.,
        1., 24., 14., 24.,  8., 56.,  2., 48.,  1.,  8.,  8.,  8., 10.,
       33., 14., 14.,  1., 24.,  1., 24., 33., 33.,  8., 33.,  1.,  8.,
        6., 12., 33.,  6., 24.,  9.,  8.,  1., 48., 24.,  6., 24.,  6.,
       33.,  8., 32., 12.,  1., 32.,  6., 24., 12., 24., 35., 49.,  2.,
       16., 49., 24., 48.,  1., 24., 16., 14.,  3.,  3., 48., 10., 24.,
       56.,  6.,  8.,  6., 14., 11., 33., 14., 12., 14., 14., 33

In [10]:
np.load("/Users/upasanathakuria/Downloads/Ytestbin_2021-11-13.npy")

array([[0., 0., 1., 0., 0., 1.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 0., 0., 1.],
       ...,
       [0., 1., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0., 0.],
       [1., 1., 1., 0., 0., 1.]])

In [11]:
np.load("/Users/upasanathakuria/Downloads/Ytest_2021-11-13.npy")

array([ 9., 30., 25., ..., 21., 52., 57.])

In [14]:
##Using 1/4th of the total training data for validation

Xtrain=np.load('Xtrain_2021-11-24.npy')
Xtest=np.load('Xtest_2021-11-24.npy')
Ytrain=np.load('Ytrain_2021-11-24.npy')
Ytrain_bin=np.load('Ytrainbin_2021-11-24.npy')
Ytest=np.load('Ytest_2021-11-24.npy')
Ytest_bin=np.load('Ytestbin_2021-11-24.npy')

n,d=Xtrain.shape
cutoff=int(n*(4/5))
Xtrain2=Xtrain[:cutoff,:]
Ytrain2=Ytrain[:cutoff]
Ytrain2_bin=Ytrain_bin[:cutoff,:]

Xval=Xtrain[cutoff:,:]
Yval=Ytrain[cutoff:]
Yval_bin=Ytrain_bin[cutoff:,:]

np.save('Xtrain_2021-11-25.npy',Xtrain2)
np.save('Ytrain_2021-11-25.npy',Ytrain2)
np.save('Ytrainbin_2021-11-25.npy',Ytrain2_bin)

np.save('Xval_2021-11-25.npy',Xval)
np.save('Yval_2021-11-25.npy',Yval)
np.save('Yvalbin_2021-11-25.npy',Yval_bin)